version: "3.5"

services:
  frontend_server:
    image: frontend
    ports:
      - 3000:3000
    container_name: frontend

  backend_server:
    image: backend
    ports:
      - 8080:8080
    container_name: backend