version: "3.8"

services:
  frontend_server:
    image: frontend
    build: ./example-frontend
    ports:
      - 3000:3000
    container_name: frontend

  backend_server:
    image: backend
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis_server
      - POSTGRES_HOST=postgres_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

    container_name: backend
    depends_on:
      - postgres_server
      - redis_server

  redis_server:
    image: redis
    restart: unless-stopped
    container_name: redis

  postgres_server:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres

  reverse:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80