version: '3.8'
services:
    frontend:
        image: frontend
        build: ./example-frontend
        ports:
          - 3000:3000

    backend: 
        image: backend
        build: ./example-backend
        ports:
          - 8080:8080
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        depends_on:
            - redis
            - postgres

    redis:
        image: redis
        restart: unless-stopped

    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        volumes:
            - ./database:/var/lib/postgresql/data
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
        environment: 
          NGINX_PORT=80
            
volumes:
  postgres:
  nginx: